import { Heebo, Alegreya } from "next/font/google";
import "./globals.css";
import Navbar from "./components/common/Navbar";

const heebo = Heebo({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
  variable: "--font-heebo",
});

const alegreya = Alegreya({
  subsets: ["latin"],
  weight: ["500", "600", "700", "800"],
  variable: "--font-alegreya",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${heebo.variable} ${alegreya.variable}`}>
      <body className="font-heebo">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
